import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { DependencyProvenanceChecker } from '../dependency-provenance-checker.service';
import { ProvenanceCheckerConfig } from '../interfaces';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Write a temp file and return its path. Cleaned up in afterEach. */
function writeTempFile(name: string, content: string): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'gg-provenance-'));
  const filePath = path.join(dir, name);
  fs.writeFileSync(filePath, content, 'utf-8');
  return filePath;
}

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

const VALID_NPM_LOCKFILE_V2 = JSON.stringify({
  lockfileVersion: 2,
  packages: {
    '': { version: '0.0.0', dev: false },
    'node_modules/lodash': {
      version: '4.17.21',
      resolved: 'https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz',
      integrity: 'sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZR/dZswXE4QSgcFfFuQ==',
    },
    'node_modules/@nestjs/common': {
      version: '10.0.0',
      resolved: 'https://registry.npmjs.org/@nestjs/common/-/common-10.0.0.tgz',
      integrity: 'sha512-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==',
    },
  },
});

const NPM_LOCKFILE_MISSING_INTEGRITY = JSON.stringify({
  lockfileVersion: 2,
  packages: {
    'node_modules/bad-pkg': {
      version: '1.0.0',
      resolved: 'https://registry.npmjs.org/bad-pkg/-/bad-pkg-1.0.0.tgz',
      // No integrity field
    },
  },
});

const NPM_LOCKFILE_UNKNOWN_REGISTRY = JSON.stringify({
  lockfileVersion: 2,
  packages: {
    'node_modules/suspect': {
      version: '1.0.0',
      resolved: 'https://evil-registry.example.com/suspect-1.0.0.tgz',
      integrity: 'sha512-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==',
    },
  },
});

const NPM_LOCKFILE_WEAK_INTEGRITY = JSON.stringify({
  lockfileVersion: 2,
  packages: {
    'node_modules/old-pkg': {
      version: '2.0.0',
      resolved: 'https://registry.npmjs.org/old-pkg/-/old-pkg-2.0.0.tgz',
      // sha1 — weak
      integrity: 'sha1-aBcDeFgHiJkLmNoPqRsTuVwXyZ0=',
    },
  },
});

const NPM_LOCKFILE_NO_RESOLVED = JSON.stringify({
  lockfileVersion: 2,
  packages: {
    'node_modules/local-only': {
      version: '0.0.1',
      // No resolved URL
      integrity: 'sha512-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==',
    },
  },
});

// Cargo.lock fixtures
const VALID_CARGO_LOCK = `
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "serde"
version = "1.0.163"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "2113ab51b87a539d849a2d77f189e84b63c27d60eb03a72eb9e2ab1ad28df7ae"

[[package]]
name = "tokio"
version = "1.28.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "94d6a[...]b2eac"
`;

// We'll replace the truncated checksum with a proper one:
const VALID_CARGO_LOCK_FULL = `
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "serde"
version = "1.0.163"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "2113ab51b87a539d849a2d77f189e84b63c27d60eb03a72eb9e2ab1ad28df7ae"

[[package]]
name = "serde_json"
version = "1.0.96"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "057d394a50403bcac12672b2b18fb387ab6d289d957dab67dd201875391e52f1"
`;

const CARGO_LOCK_MISSING_CHECKSUM = `
[[package]]
name = "some-crate"
version = "0.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
`;

const CARGO_LOCK_UNKNOWN_SOURCE = `
[[package]]
name = "shady-crate"
version = "0.1.0"
source = "registry+https://evil.example.com/crates-io-index"
checksum = "2113ab51b87a539d849a2d77f189e84b63c27d60eb03a72eb9e2ab1ad28df7ae"
`;

const CARGO_LOCK_PATH_DEP = `
[[package]]
name = "my-workspace-crate"
version = "0.0.1"
`;

const CARGO_LOCK_MALFORMED_CHECKSUM = `
[[package]]
name = "corrupted"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "not-a-valid-hash!!!"
`;

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('DependencyProvenanceChecker', () => {
  let checker: DependencyProvenanceChecker;

  beforeEach(() => {
    checker = new DependencyProvenanceChecker();
  });

  // ── npm lockfile checks ───────────────────────────────────────────────────

  describe('checkNpmLockfile()', () => {
    it('passes for a valid lockfile with known registry and sha512 integrity', async () => {
      const lockfile = writeTempFile('package-lock.json', VALID_NPM_LOCKFILE_V2);
      const result = await checker.checkNpmLockfile(lockfile);

      expect(result.passed).toBe(true);
      expect(result.totalChecked).toBe(2);
      expect(result.violations).toHaveLength(0);
      expect(result.records.every((r) => r.integrityVerified === true)).toBe(true);
    });

    it('flags a CRITICAL violation when integrity is missing', async () => {
      const lockfile = writeTempFile('package-lock.json', NPM_LOCKFILE_MISSING_INTEGRITY);
      const result = await checker.checkNpmLockfile(lockfile);

      const criticals = result.violations.filter((v) => v.severity === 'critical');
      expect(criticals).toHaveLength(1);
      expect(criticals[0].packageName).toBe('bad-pkg');
      expect(result.passed).toBe(false);
    });

    it('flags a HIGH violation when resolved URL uses an unknown registry', async () => {
      const lockfile = writeTempFile('package-lock.json', NPM_LOCKFILE_UNKNOWN_REGISTRY);
      const result = await checker.checkNpmLockfile(lockfile);

      const highs = result.violations.filter((v) => v.severity === 'high');
      expect(highs).toHaveLength(1);
      expect(highs[0].packageName).toBe('suspect');
      expect(result.passed).toBe(false);
    });

    it('flags a MEDIUM violation when a weak integrity algorithm (sha1) is used', async () => {
      const lockfile = writeTempFile('package-lock.json', NPM_LOCKFILE_WEAK_INTEGRITY);
      const result = await checker.checkNpmLockfile(lockfile, { failOnSeverity: 'medium' });

      const mediums = result.violations.filter((v) => v.severity === 'medium');
      expect(mediums).toHaveLength(1);
      expect(mediums[0].packageName).toBe('old-pkg');
      expect(result.passed).toBe(false);
    });

    it('does NOT fail when failOnSeverity is set to critical and only medium violations exist', async () => {
      const lockfile = writeTempFile('package-lock.json', NPM_LOCKFILE_WEAK_INTEGRITY);
      const result = await checker.checkNpmLockfile(lockfile, { failOnSeverity: 'critical' });

      // Medium violation present, but threshold is 'critical' → should pass.
      expect(result.passed).toBe(true);
      expect(result.violations.some((v) => v.severity === 'medium')).toBe(true);
    });

    it('flags a HIGH violation when resolved URL is absent', async () => {
      const lockfile = writeTempFile('package-lock.json', NPM_LOCKFILE_NO_RESOLVED);
      const result = await checker.checkNpmLockfile(lockfile);

      const highs = result.violations.filter((v) => v.severity === 'high');
      expect(highs.length).toBeGreaterThanOrEqual(1);
      expect(result.passed).toBe(false);
    });

    it('skips packages in the exclude list', async () => {
      const lockfile = writeTempFile('package-lock.json', NPM_LOCKFILE_MISSING_INTEGRITY);
      const result = await checker.checkNpmLockfile(lockfile, { exclude: ['bad-pkg'] });

      expect(result.totalChecked).toBe(0);
      expect(result.violations).toHaveLength(0);
      expect(result.passed).toBe(true);
    });

    it('respects maxPackages limit', async () => {
      const lockfile = writeTempFile('package-lock.json', VALID_NPM_LOCKFILE_V2);
      const result = await checker.checkNpmLockfile(lockfile, { maxPackages: 1 });

      expect(result.totalChecked).toBe(1);
    });

    it('throws when the lockfile does not exist', async () => {
      await expect(
        checker.checkNpmLockfile('/nonexistent/path/package-lock.json'),
      ).rejects.toThrow('Lockfile not found');
    });

    it('includes an ISO-8601 checkedAt timestamp in results', async () => {
      const lockfile = writeTempFile('package-lock.json', VALID_NPM_LOCKFILE_V2);
      const result = await checker.checkNpmLockfile(lockfile);

      expect(new Date(result.checkedAt).toISOString()).toBe(result.checkedAt);
    });
  });

  // ── Cargo lockfile checks ─────────────────────────────────────────────────

  describe('checkCargoLockfile()', () => {
    it('passes for a valid Cargo.lock with crates.io source and valid checksums', async () => {
      const lockfile = writeTempFile('Cargo.lock', VALID_CARGO_LOCK_FULL);
      const result = await checker.checkCargoLockfile(lockfile);

      expect(result.passed).toBe(true);
      expect(result.violations).toHaveLength(0);
      expect(result.totalChecked).toBe(2);
    });

    it('flags a CRITICAL violation when crates.io package is missing checksum', async () => {
      const lockfile = writeTempFile('Cargo.lock', CARGO_LOCK_MISSING_CHECKSUM);
      const result = await checker.checkCargoLockfile(lockfile);

      const criticals = result.violations.filter((v) => v.severity === 'critical');
      expect(criticals).toHaveLength(1);
      expect(criticals[0].packageName).toBe('some-crate');
      expect(result.passed).toBe(false);
    });

    it('flags a HIGH violation when source is an unrecognised registry', async () => {
      const lockfile = writeTempFile('Cargo.lock', CARGO_LOCK_UNKNOWN_SOURCE);
      const result = await checker.checkCargoLockfile(lockfile);

      const highs = result.violations.filter((v) => v.severity === 'high');
      expect(highs).toHaveLength(1);
      expect(highs[0].packageName).toBe('shady-crate');
      expect(result.passed).toBe(false);
    });

    it('flags an INFO violation for path/workspace dependencies (no source)', async () => {
      const lockfile = writeTempFile('Cargo.lock', CARGO_LOCK_PATH_DEP);
      // failOnSeverity = 'critical' so info-level doesn't fail
      const result = await checker.checkCargoLockfile(lockfile, { failOnSeverity: 'critical' });

      const infos = result.violations.filter((v) => v.severity === 'info');
      expect(infos).toHaveLength(1);
      expect(result.passed).toBe(true);
    });

    it('flags a HIGH violation for a malformed checksum value', async () => {
      const lockfile = writeTempFile('Cargo.lock', CARGO_LOCK_MALFORMED_CHECKSUM);
      const result = await checker.checkCargoLockfile(lockfile);

      const highs = result.violations.filter((v) => v.severity === 'high');
      expect(highs).toHaveLength(1);
      expect(highs[0].packageName).toBe('corrupted');
    });

    it('skips packages in the exclude list', async () => {
      const lockfile = writeTempFile('Cargo.lock', CARGO_LOCK_MISSING_CHECKSUM);
      const result = await checker.checkCargoLockfile(lockfile, { exclude: ['some-crate'] });

      expect(result.violations).toHaveLength(0);
      expect(result.passed).toBe(true);
    });

    it('throws when the lockfile does not exist', async () => {
      await expect(
        checker.checkCargoLockfile('/nonexistent/path/Cargo.lock'),
      ).rejects.toThrow('Lockfile not found');
    });
  });

  // ── File integrity verification ───────────────────────────────────────────

  describe('verifyFileIntegrity()', () => {
    it('returns true when the file hash matches the expected SRI value', () => {
      const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'gg-integrity-'));
      const filePath = path.join(dir, 'test.txt');
      const content = 'hello world';
      fs.writeFileSync(filePath, content);

      // Pre-computed sha256 for "hello world"
      const expectedSha256Base64 = 'uU0nuZNNPgilLlLX2n2r+sSE7+N6U4DukIj3rOLvzek=';
      const sriHash = `sha256-${expectedSha256Base64}`;

      expect(checker.verifyFileIntegrity(filePath, sriHash)).toBe(true);
    });

    it('returns false when the file content does not match the SRI hash', () => {
      const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'gg-integrity-'));
      const filePath = path.join(dir, 'test.txt');
      fs.writeFileSync(filePath, 'tampered content');

      const sriHash = 'sha256-uU0nuZNNPgilLlLX2n2r+sSE7+N6U4DukIj3rOLvzek='; // hash of "hello world"

      expect(checker.verifyFileIntegrity(filePath, sriHash)).toBe(false);
    });

    it('returns false for a malformed SRI hash string', () => {
      const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'gg-integrity-'));
      const filePath = path.join(dir, 'test.txt');
      fs.writeFileSync(filePath, 'data');

      expect(checker.verifyFileIntegrity(filePath, 'not-a-valid-hash')).toBe(false);
    });

    it('returns false when the file does not exist', () => {
      expect(checker.verifyFileIntegrity('/no/such/file.txt', 'sha256-abc')).toBe(false);
    });
  });

  // ── Boundary / edge cases ─────────────────────────────────────────────────

  describe('edge cases', () => {
    it('handles an npm lockfile with no packages gracefully', async () => {
      const lockfile = writeTempFile(
        'package-lock.json',
        JSON.stringify({ lockfileVersion: 2, packages: {} }),
      );
      const result = await checker.checkNpmLockfile(lockfile);

      expect(result.passed).toBe(true);
      expect(result.totalChecked).toBe(0);
      expect(result.violations).toHaveLength(0);
    });

    it('handles a Cargo.lock with no [[package]] sections gracefully', async () => {
      const lockfile = writeTempFile('Cargo.lock', '# empty\nversion = 3\n');
      const result = await checker.checkCargoLockfile(lockfile);

      expect(result.passed).toBe(true);
      expect(result.totalChecked).toBe(0);
    });

    it('throws a descriptive error on invalid JSON in npm lockfile', async () => {
      const lockfile = writeTempFile('package-lock.json', '{ not valid json }');
      await expect(checker.checkNpmLockfile(lockfile)).rejects.toThrow('Failed to parse lockfile');
    });

    it('includes remediation advice for each violation', async () => {
      const lockfile = writeTempFile('package-lock.json', NPM_LOCKFILE_MISSING_INTEGRITY);
      const result = await checker.checkNpmLockfile(lockfile);

      for (const v of result.violations) {
        expect(typeof v.remediation).toBe('string');
        expect(v.remediation!.length).toBeGreaterThan(0);
      }
    });

    it('includes the package ecosystem in every violation', async () => {
      const lockfile = writeTempFile('package-lock.json', NPM_LOCKFILE_MISSING_INTEGRITY);
      const result = await checker.checkNpmLockfile(lockfile);

      for (const v of result.violations) {
        expect(v.ecosystem).toBe('npm');
      }
    });
  });
});
