import { expect } from "chai";
import { network } from "hardhat";

const MAX_UINT256 = (1n << 256n) - 1n;

/** Deterministic PRNG (mulberry32-style) so failures are reproducible. */
function makeRng(seed: number) {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function randomBigUint(rng: () => number, maxBits: number): bigint {
  const bits = Math.floor(rng() * (maxBits + 1));
  if (bits === 0) return 0n;
  let value = 1n; // ensure top bit so we actually explore `bits`-sized numbers
  for (let i = 1; i < bits; i++) {
    value = (value << 1n) | (rng() < 0.5 ? 0n : 1n);
  }
  return value;
}

/** Reference implementation using BigInt, which never overflows. */
function referenceMulDivDown(x: bigint, y: bigint, denominator: bigint): bigint | "DivisionByZero" | "Overflow" {
  if (denominator === 0n) return "DivisionByZero";
  const result = (x * y) / denominator;
  if (result > MAX_UINT256) return "Overflow";
  return result;
}

describe("YulMathLib.mulDivDown", () => {
  async function deployFixture() {
    const { ethers } = await network.create();
    const harnessFactory = await ethers.getContractFactory("YulMathLibHarness");
    const deployed = await harnessFactory.deploy();

    // `DivisionByZero`/`MulDivOverflow` are declared on the `YulMathLib`
    // library, not on the harness itself, so the harness's own ABI (as
    // generated by solc) doesn't list them even though its bytecode can
    // revert with them (the library's internal function is inlined into
    // the harness). Merge in the library's error-only ABI so
    // `revertedWithCustomError` can decode them.
    const libraryFactory = await ethers.getContractFactory("YulMathLib");
    const combinedInterface = new ethers.Interface([
      ...deployed.interface.fragments,
      ...libraryFactory.interface.fragments,
    ]);
    const harness = new ethers.Contract(await deployed.getAddress(), combinedInterface, deployed.runner);

    return { harness };
  }

  it("matches the BigInt reference on hand-picked edge cases", async () => {
    const { harness } = await deployFixture();

    const cases: Array<[bigint, bigint, bigint]> = [
      [0n, 0n, 1n],
      [0n, 12345n, 1n],
      [12345n, 0n, 1n],
      [1n, 1n, 1n],
      [10n, 3n, 3n], // floor rounding: 30/3 = 10 exactly
      [10n, 1n, 3n], // floor rounding: 10/3 = 3.33 -> 3
      [MAX_UINT256, 1n, 1n],
      [MAX_UINT256, MAX_UINT256, MAX_UINT256], // = MAX_UINT256 exactly
      [MAX_UINT256, MAX_UINT256 - 1n, MAX_UINT256], // product overflows 256 bits, result still fits
      [2n ** 200n, 2n ** 200n, 2n ** 150n], // product overflows 256 bits, result fits
    ];

    for (const [x, y, denominator] of cases) {
      const expected = referenceMulDivDown(x, y, denominator);
      if (expected === "DivisionByZero" || expected === "Overflow") {
        throw new Error("test setup error: edge case list should only contain valid results");
      }
      const actual: bigint = await harness.mulDivDown(x, y, denominator);
      expect(actual, `mulDivDown(${x}, ${y}, ${denominator})`).to.equal(expected);
    }
  });

  it("reverts with DivisionByZero() when denominator == 0", async () => {
    const { harness } = await deployFixture();
    await expect(harness.mulDivDown(5n, 7n, 0n)).to.be.revertedWithCustomError(harness, "DivisionByZero");
    await expect(harness.mulDivDown(0n, 0n, 0n)).to.be.revertedWithCustomError(harness, "DivisionByZero");
  });

  it("reverts with MulDivOverflow() when the true result does not fit in 256 bits", async () => {
    const { harness } = await deployFixture();
    // x * y is close to (2**256)^2 in magnitude; dividing by 1 obviously can't fit back into 256 bits.
    await expect(harness.mulDivDown(MAX_UINT256, MAX_UINT256, 1n)).to.be.revertedWithCustomError(
      harness,
      "MulDivOverflow",
    );
    // denominator smaller than the high word of the 512-bit product.
    await expect(harness.mulDivDown(MAX_UINT256, MAX_UINT256, 2n)).to.be.revertedWithCustomError(
      harness,
      "MulDivOverflow",
    );
  });

  it("fuzzes 250 random (x, y, denominator) triples against the BigInt reference", async () => {
    const { harness } = await deployFixture();
    const rng = makeRng(0xc0ffee);

    const TOTAL_CASES = 250;
    let checked = 0;
    let divByZeroChecked = 0;
    let overflowChecked = 0;
    let exactChecked = 0;
    let flooredChecked = 0;

    for (let i = 0; i < TOTAL_CASES; i++) {
      // Mix magnitudes: mostly full-width random 256-bit-ish numbers, but
      // periodically bias toward small numbers/denominators so we exercise
      // ordinary "no overflow" arithmetic and non-trivial floor rounding,
      // not just the overflow edge.
      const bias = i % 5;
      let x: bigint;
      let y: bigint;
      let denominator: bigint;

      if (bias === 0) {
        // Small values: exercises plain floor-rounding behavior heavily.
        x = randomBigUint(rng, 32);
        y = randomBigUint(rng, 32);
        denominator = randomBigUint(rng, 32);
      } else if (bias === 1) {
        // denominator = 0 edge case.
        x = randomBigUint(rng, 256);
        y = randomBigUint(rng, 256);
        denominator = 0n;
      } else if (bias === 2) {
        // x or y = 0 edge case.
        x = rng() < 0.5 ? 0n : randomBigUint(rng, 256);
        y = x === 0n ? randomBigUint(rng, 256) : 0n;
        denominator = randomBigUint(rng, 256) + 1n;
      } else {
        // Full-width random values: likely to overflow 256 bits when
        // multiplied, exercising the 512-bit path (both the case where the
        // final result still fits, and the case where it doesn't).
        x = randomBigUint(rng, 256);
        y = randomBigUint(rng, 256);
        denominator = randomBigUint(rng, 256);
      }

      const expected = referenceMulDivDown(x, y, denominator);
      checked++;

      if (expected === "DivisionByZero") {
        divByZeroChecked++;
        await expect(
          harness.mulDivDown(x, y, denominator),
          `mulDivDown(${x}, ${y}, ${denominator}) should revert with DivisionByZero`,
        ).to.be.revertedWithCustomError(harness, "DivisionByZero");
        continue;
      }

      if (expected === "Overflow") {
        overflowChecked++;
        await expect(
          harness.mulDivDown(x, y, denominator),
          `mulDivDown(${x}, ${y}, ${denominator}) should revert with MulDivOverflow`,
        ).to.be.revertedWithCustomError(harness, "MulDivOverflow");
        continue;
      }

      if (x * y % denominator === 0n) {
        exactChecked++;
      } else {
        flooredChecked++;
      }

      const actual: bigint = await harness.mulDivDown(x, y, denominator);
      expect(actual, `mulDivDown(${x}, ${y}, ${denominator})`).to.equal(expected);
    }

    expect(checked).to.equal(TOTAL_CASES);
    // Make sure the fuzz run actually exercised every interesting category
    // at least once, so this isn't accidentally a no-op test.
    expect(divByZeroChecked, "should have exercised denominator == 0").to.be.greaterThan(0);
    expect(overflowChecked, "should have exercised the overflow-revert path").to.be.greaterThan(0);
    expect(exactChecked, "should have exercised exact (non-floored) division").to.be.greaterThan(0);
    expect(flooredChecked, "should have exercised floor-rounding division").to.be.greaterThan(0);
  });
});
